FROM python:3.9

WORKDIR /app

COPY ../test-3/requirements.txt .
COPY ../test-3/test-3.py .
COPY ../dataset/ds-users.json .
COPY ../dataset/ds-sentences.json .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "test-3.py"]