FROM python:3.8.10

WORKDIR /app

# Copy the requirements file first
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt 

# Copy the dataset and application code
#COPY ../dataset /app/dataset
COPY . .

CMD ["python3", "test-.py"]
