FROM python:3.9

WORKDIR /app

COPY ../test-2/requirements.txt .
COPY ../test-2/test-2.py .
COPY ../dataset/ds-users.json .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "test-2.py"]