# Use an official base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app/Exam_2/test-1

# Copy the requirements file to the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the dataset directory to the container
COPY ../dataset ./dataset

# Optionally expose a port if needed
EXPOSE 8080 

# Define the command to run your application
CMD ["python", "test-1.py"] 
