version: "3.3"
services:
  mongodb:
    image : mongo:6.0-focal
    container_name: my_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: datascientest
      MONGO_INITDB_ROOT_PASSWORD: dst123
    volumes:
      - ./sample_training:/data/db
    ports:
      - 27017:27017